---
- hosts: appservers
  vars:
    user: root
    daemon: /usr/bin/java
    pidfile: /var/run/homefront.pid
    daemon_opts: "-jar /root/deploy/homefront.jar 3000"
    service_name: homefront
# homefront_user, homefront_pwd, homefront_db_port vars are expected to come from somewhere, e.g. the inventory.

  tasks:
  - name: Stop the service if it already exists
    action: service name=homefront state=stopped
  - name: Create deploy directory
    file: path=/root/deploy state=directory
  - name: Copy homefront.jar
    action: copy src=../target/homefront.jar dest=/root/deploy/homefront.jar mode=0751
  - name: Add homefront init.d daemon script
    action: template src=templates/init.d-template.j2 dest=/etc/init.d/homefront mode=0751
  - name: Ensure my daemon homefront is started
    action: service name=homefront state=started
  - wait_for: port=3000 timeout=30
